apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-calculator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-calculator
  template:
    metadata:
      labels:
        app: flask-calculator
    spec:
      containers:
        - name: flask-calculator
          image: flask-calculator:v1   # ⚠️ Must match the Docker image name
          imagePullPolicy: Never       # Don't pull from Docker Hub if it's local
          ports:
            - containerPort: 5000
